name = "SquareModels"
uuid = "8f61fe60-8cc6-11ec-3043-2171a73045bd"
version = "0.1.0"
authors = ["Martin Kirk Bonde <martin@bonde.dk>"]

[deps]
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Dictionaries = "0.4"
Ipopt = "1.14.0"
JuMP = "1"
Lazy = "0.15"
StatsBase = "0.34"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
